"""TLS for the web UI: a self-signed cert by default the moment it is exposed.

The problem this solves is narrow and worth stating plainly. With ``auth=pam`` the
login sends a real host password over the wire, and until now that wire was plain
HTTP -- so anyone on the LAN could read the password by watching. These are
appliances with no reverse proxy in front of them; the device *is* the endpoint,
so the TLS has to live here.

What a self-signed cert does and does not buy is the whole design, so it is not
buried:

* It stops a **passive** eavesdropper -- someone sniffing the network but not
  injecting -- from reading the password or the session cookie. That is the hole
  above, and self-signed closes it.
* It does **not** stop an **active** MITM. The browser warns on a self-signed
  cert, the operator clicks through, and an attacker who presents *their own*
  self-signed cert gets clicked through identically. Every header we then send --
  the ``Secure`` cookie flag, anything -- rides a channel the attacker owns, so
  none of it is trustworthy. Self-signed is encryption, not authentication.

The MITM answer is a cert the browser can *validate* against a trust anchor: point
``SPIRICONFIG_TLS_CERT``/``SPIRICONFIG_TLS_KEY`` at a per-device cert from a CA the
fleet trusts. That is the only path on which the attacker's substitute cert is
*rejected* rather than clicked through, and so the only path where HSTS is safe --
which is exactly why :func:`resolve` turns HSTS on for a provided cert and off for
a generated one (HSTS on a self-signed origin forbids the very click-through the
operator needs, and locks them out on the next visit).

The cert is generated by shelling out to ``openssl``, like everything else here:
the command is one a person could have run by hand, and :func:`selfsigned_command`
returns it rather than running it, so the interesting part is testable without a
cert authority anywhere in sight.
"""

from __future__ import annotations

import os
import socket
from dataclasses import dataclass
from pathlib import Path

from loguru import logger

from spiriconfig.commands import Command, run

log = logger.bind(component="tls")


def state_dir() -> Path:
    """Where generated TLS material is kept, so it survives a restart.

    A cert that regenerates on every boot is a fresh browser warning on every boot
    and defeats any attempt to pin it, so it has to be persisted. ``$STATE_DIRECTORY``
    is what systemd sets (and creates, correctly owned) for a unit with
    ``StateDirectory=spiriconfig`` -- ``/var/lib/spiriconfig`` for the system service,
    ``~/.local/state/spiriconfig`` for the user one. Outside systemd we fall back to
    the XDG state home, so a plain checkout still has somewhere sane to write.
    """
    runtime = os.environ.get("STATE_DIRECTORY")
    if runtime:
        # systemd may hand over a colon-separated list; the first is ours.
        return Path(runtime.split(":", 1)[0])
    xdg = os.environ.get("XDG_STATE_HOME")
    base = Path(xdg) if xdg else Path.home() / ".local" / "state"
    return base / "spiriconfig"


def _cert_paths() -> tuple[Path, Path]:
    """The (cert, key) pair a generated self-signed cert lives at."""
    tls = state_dir() / "tls"
    return tls / "cert.pem", tls / "key.pem"


@dataclass(frozen=True, slots=True)
class TlsPlan:
    """What TLS to serve, decided before the server starts.

    ``certfile``/``keyfile`` are None when the UI stays on plain HTTP (a loopback
    dev session, or ``tls=off`` because a real proxy terminates TLS in front).
    ``generate`` is set only for the self-signed path, where the files may not exist
    yet. ``hsts`` is true only for a provided cert -- never for self-signed, where it
    would lock the operator out (see the module docstring).
    """

    certfile: Path | None
    keyfile: Path | None
    generate: bool = False
    hsts: bool = False

    @property
    def enabled(self) -> bool:
        """Whether the UI is served over HTTPS at all."""
        return self.certfile is not None

    @property
    def scheme(self) -> str:
        return "https" if self.enabled else "http"


def resolve(
    *,
    mode: str,
    cert: str | None,
    key: str | None,
    is_loopback: bool,
) -> TlsPlan:
    """Decide what TLS to serve from the settings, without touching the disk.

    The rules, in order:

    * ``mode == "off"`` -- plain HTTP, no matter what. For the deployment that has
      its own TLS-terminating proxy and does not want us encrypting twice.
    * a provided cert *and* key -- use them, and turn HSTS on: this is the only
      cert the browser can actually validate, so it is the only one HSTS is safe on.
    * exposed (not loopback) with no provided cert -- generate and serve a
      self-signed cert, HSTS off.
    * loopback with no provided cert -- plain HTTP, because a dev checkout on
      ``127.0.0.1`` is not exposed and a cert warning there is pure friction.

    A cert given without its key (or the reverse) is a misconfiguration, not half a
    setup: logged, then ignored, so we fall through to the automatic behaviour rather
    than starting with a broken half-provided pair.
    """
    if mode == "off":
        return TlsPlan(None, None)

    if cert and key:
        return TlsPlan(Path(cert), Path(key), generate=False, hsts=True)
    if cert or key:
        log.error(
            "SPIRICONFIG_TLS_CERT and SPIRICONFIG_TLS_KEY must be set together; "
            "only one was, so both are ignored"
        )

    if not is_loopback:
        cert_path, key_path = _cert_paths()
        return TlsPlan(cert_path, key_path, generate=True, hsts=False)

    return TlsPlan(None, None)


def default_sans(host: str) -> list[str]:
    """Best-effort subject-alternative names for a generated cert.

    We cannot reliably know every address a browser will reach the device on -- an
    appliance's LAN IP is handed out by DHCP and changes -- so this is a floor, not a
    guarantee: the machine's hostname, localhost, and the loopback IPs, plus the bound
    host itself when it is a concrete address rather than a wildcard. A name the cert
    does not cover is just one more warning the operator clicks through, which on a
    self-signed cert they are doing regardless.
    """
    sans = [
        "DNS:localhost",
        "IP:127.0.0.1",
        "IP:::1",
    ]
    hostname = socket.gethostname()
    if hostname and hostname != "localhost":
        sans.insert(0, f"DNS:{hostname}")
    if host not in {"0.0.0.0", "::", "localhost"} and not host.startswith("127."):
        prefix = "IP" if _looks_like_ip(host) else "DNS"
        entry = f"{prefix}:{host}"
        if entry not in sans:
            sans.append(entry)
    return sans


def _looks_like_ip(host: str) -> bool:
    """Whether ``host`` is a literal IP, so the SAN entry is ``IP:`` not ``DNS:``."""
    for family in (socket.AF_INET, socket.AF_INET6):
        try:
            socket.inet_pton(family, host)
            return True
        except OSError:
            continue
    return False


def selfsigned_command(
    cert: Path,
    key: Path,
    sans: list[str],
    *,
    openssl_bin: str = "openssl",
    days: int = 3650,
) -> Command:
    """The ``openssl`` line that writes a self-signed cert and its key.

    ``-nodes`` leaves the key unencrypted, which an unattended service needs -- there
    is no one at a terminal to type a passphrase when systemd starts us at boot. The
    key's secrecy therefore rests on file permissions, which :func:`ensure_selfsigned`
    sets. Ten years by default: a self-signed appliance cert that expires is an outage
    with no upside, since re-issuing it is no more trustworthy than the first one.
    """
    return Command(
        argv=[
            openssl_bin,
            "req",
            "-x509",
            "-newkey",
            "rsa:2048",
            "-keyout",
            str(key),
            "-out",
            str(cert),
            "-days",
            str(days),
            "-nodes",
            "-subj",
            "/CN=SpiriConfig",
            "-addext",
            f"subjectAltName={','.join(sans)}",
        ]
    )


def ensure_selfsigned(plan: TlsPlan, host: str, *, openssl_bin: str = "openssl") -> None:
    """Generate the self-signed cert if it is not already on disk.

    Idempotent: an existing pair is reused untouched, so a restart keeps the same
    cert (and the operator does not re-approve a new one every boot). The directory
    is created ``0700`` and the key left ``0600`` -- an unencrypted key is only as
    safe as the permissions on it.
    """
    if not plan.generate or plan.certfile is None or plan.keyfile is None:
        return
    if plan.certfile.exists() and plan.keyfile.exists():
        return

    plan.certfile.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    sans = default_sans(host)
    log.info("generating a self-signed TLS cert at {} (SAN: {})", plan.certfile, ", ".join(sans))
    run(
        selfsigned_command(plan.certfile, plan.keyfile, sans, openssl_bin=openssl_bin),
        log=log,
    ).check()
    plan.keyfile.chmod(0o600)


__all__ = [
    "TlsPlan",
    "default_sans",
    "ensure_selfsigned",
    "resolve",
    "selfsigned_command",
    "state_dir",
]
